### PR TITLE
Fix distributor ID to not be title case unless upstream

### LINKED ISSUE #205: Upper case letter E for GRUB boot menu entry
## What Happened

When other operating systems are present and Odin is installed the resulting boot menu displays "Elementary" with a capital letter E.

## Expected Behavior

The boot menu entry should be "elementary" with a lower case letter e.

## Platform Information

Odin stable with latest updates.

Output of the `lsb_release` command also displays Elementary with a capital E when a couple of places at least seem to have the name with the lower case name such as in /etc/os-release or /etc/lsb-release

### PR DESCRIPTION
**Pull request by vjr**
Fixes #205

### CODE REVIEW

**Comment by vjr** [comment]
Fixes #205 

Tested with mutiple Windows/Linux installations on the same drive and also by running and comparing command output `lsb_release` with and without the `-u` option after editing `/etc/upstream-release/lsb-release` to temporarily set the ID to lowercase `ubuntu`

The main elementary grub boot entry is now `elementary` instead of `Elementary`

**Comment by vjr** [comment]
Silly me... fixing this PR asap...

**Comment by danrabbit** [comment]
Hm, thinking about this more, does this mean our GRUB configuration is using `ID` where it should be using `PRETTY_NAME`? Would it make more sense to resolve that in our GRUB so we don't have to carry another patch here?

**Comment by vjr** [comment]
Is this PR resulting in addition of another patch to upstream package?

I guess I could look into using PRETTY_NAME on the grub side of things, give me a few days.

**Comment by vjr** [comment]
@danrabbit  there is already a patched `lsb-focal-patched` branch to which this PR adds a diff to the existing `lsb_release.py` modifications so no new patch file being added.

Do we really want to use `PRETTY_NAME` still? That would be a simple change to `/etc/default/grub` to use the `-d` option instead of `-i` passed to `lsb_release` to set the `GRUB_DISTRIBUTOR` var which I can create a PR if you want.

It's a matter of whether you want to show just `elementary` in the grub boot menu as in previous releases or `elementary OS 6 Odin` going forward, so which is it?

**Comment by davidmhewitt** [comment]
Going to close this in favour of #222 . I don't like the idea of changing what `lsb_release` returns.

There may be random scripts online that target elementary and use `lsb_release` (and the specific casing it returns) to detect elementary.

**Pull request closed without merging**
