### PR TITLE
Update touchegg.conf

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes https://github.com/elementary/triage/issues/44

From Cassidy's gist here: https://gist.githubusercontent.com/cassidyjames/85ff4079572bc07c74dd8a5770972733/raw/8148dcb01bf695e68d2e07b991a71094e5ef5d24/touchegg.conf

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit a couple of open questions I have (which @JoseExposito might be able to answer):

1. Should Touchegg somehow follow the "natural scrolling" preference? Maybe that can handled in Touchegg itself.
2. Can we get the accent color from the stylesheet instead of hardcoding something here (in this case, a neutral gray)?

Right now this configuration assumes natural scrolling but I'm sure people would be annoyed if they weren't using natural scrolling. Accent color is less big of a deal, but maybe something we should look into.

**Comment by danrabbit** [comment]
Re: accent color, I filed an issue in Touchegg but it sounds like José doesn't want to add a Gtk dependency there. But if we merge the gala stuff then we can do whatever we want here anyways

I guess you should probably open an issue report against Touchegg for natural scrolling pref

**Review by cassidyjames — APPROVED** [review]

**Comment by JoseExposito** [comment]
Hi!

I created a milestone so the next release (v2.0.3) to address the main issues present in the elementary OS integration. Both Touchégg itself and Gala. Feel free to add more issues, I hope I have time to fix them before the release of Odin:
https://github.com/JoseExposito/touchegg/milestone/2

Also, I'll like to include this issue in v2.0.3 and I'll really appreciate your help: https://github.com/JoseExposito/touchegg/issues/368
There is an ongoing discussion of how to allow distros to upgrade the default configuration. Comments are welcome, as you have way more experience on this topics.

**Comment by JoseExposito** [comment]
Just fixed the issue with natural scrolling: https://github.com/JoseExposito/touchegg/issues/382
So once I release v2.0.3 I'll try to submit a pull request to change this the config to look like:

```xml
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>
```

Also, I added the type of the device that generated the gestures (touchscreen or touchpad) so Gala can make use of it. I'll update my PR as soon as possible.

**Comment by JoseExposito** [comment]
Just for the record, here is the PR https://github.com/elementary/os-patches/pull/141

**Pull request merged**
